version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - './data:/data/db'
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
  FrontEnd:
    # if something fails or the server is restarted, the container will restart
    restart: always 
    container_name: 3102-uplink
    image: 3102-uplink
    volumes:
      - './uploads:/uploads'
    build: 
      # build the iris clasifier image from the Dockerfile in the current directory
      context: FrontEnd
  qnatransformer_api:
    build: qnatransformer
    container_name: Transformer
    ports:
      - 8888:8888
      - 9001:9001
    command: >
        jupyter kernelgateway 
        --KernelGatewayApp.api=notebook-http
        --KernelGatewayApp.ip=0.0.0.0
        --KernelGatewayApp.port=8888
        --KernelGatewayApp.seed_uri='/home/jovyan/work/qnatransformer.ipynb'
  Caption:
    container_name: CaptionTransformer
    ports:
      - 8889:8889
      - 9002:9002
