version: '3.1'

services:
  FrontEnd:
    # if something fails or the server is restarted, the container will restart
    restart: always 
    container_name: 3102-uplink
    image: 3102-uplink
    volumes:
      - './uploads:/uploads'
    build: 
      # build the iris clasifier image from the Dockerfile in the current directory
      context: FrontEnd
  qnatransformer_api:
    build: qnatransformer
    container_name: Transformer
    ports:
      - 8888:8888
  caption:
    build: Caption
    container_name: captions
    ports:
      - 8080:8080

networks:
  default:
    name: 3102-network